baseURL = 'https://currentlyblocked.github.io/'
languageCode = 'en-gb'
title = 'CurrentlyBlocked'
theme = "hello-friend-ng"
pagination.pagerSize = 10

[markup.goldmark.renderer]
    unsafe = true

[params]
  dateform         = "Jan 2, 2006"
  dateformShort    = "Jan 2"
  dateformNum      = "2006-01-02"
  dateformNumTime  = "2006-01-02 15:04"

  portrait.path = "/img/logo.png"
  homeSubtitle = "Senior SRE | Doing my best to build simple systems for complex problems."

  defaultTheme = "dark"
  showReadTime = true
  enableSharingButtons = false
  enableGlobalLanguageMenu = false

  # Metadata
#   description = "Pragmatic Site Reliability Engineering and Security."
#   keywords = "SRE, Security, Go, Cloud, Infrastructure"

# [taxonomies]
#     category = "blog"
#     tag      = "tags"

[languages]
  [languages.en]
    title = "I'm CurrentlyBlocked"
    copyright = "By CurrentlyBlocked."
    readOtherPosts = "Read more"

    [languages.en.params]
      subtitle = ""

      [languages.en.params.logo]
        path = "/img/logo.png"
        alt = "Currently blocked"

  # --- MAIN NAVIGATION ---
[menus]

  [[menus.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
    hasChildren = true

  [[menus.main]]
    identifier = "overview"
    name = "Overview"
    url = "/about/overview"
    weight = 11
    parent = "about"

  [[menus.main]]
    identifier = "experience"
    name = "Experience"
    url = "/about/experience"
    weight = 12
    parent = "about"

  [[menus.main]]
    identifier = "github"
    name       = "GitHub"
    url        = "https://github.com/currentlyblocked"
    weight = 20
    [menus.main.params]
      newtab = true

  # [[menus.main]]
  #   identifier = "blog"
  #   name       = "Posts"
  #   url        = "/posts"

  [[menus.main]]
    identifier = "toolbox"
    name  = "Toolbox"
    url = "/toolbox/"
    hasChildren = true
    weight = 30

  [[menus.main]]
    identifier = "ratio"
    name = "Ratio"
    url = "/toolbox/ratio/"
    parent = "toolbox"

  [[menus.main]]
    identifier = "wisdom"
    name       = "Reading List"
    url        = "/reading"
    weight = 40
